"""Digest report generator — shareable trend summaries.

Generates a beautiful digest report in Markdown or HTML that can be
shared via email, Slack, Discord, or social media.
"""

from datetime import datetime, timezone
from typing import Optional

from .models import IntelItem, SourceType, TrendSnapshot


SOURCE_EMOJI = {
    SourceType.GITHUB: "🐙",
    SourceType.HACKERNEWS: "🔶",
    SourceType.REDDIT: "🤖",
    SourceType.ARXIV: "📄",
    SourceType.RSS: "📡",
    SourceType.PRODUCTHUNT: "🚀",
}


def generate_digest_markdown(
    snapshot: TrendSnapshot,
    title: Optional[str] = None,
    top_n: int = 10,
    include_keywords: bool = True,
    include_stats: bool = True,
) -> str:
    """Generate a shareable Markdown digest from a trend snapshot."""
    ts = snapshot.timestamp.strftime("%Y-%m-%d %H:%M UTC")
    title = title or f"📡 Trend Radar Digest — {ts}"

    lines = [
        f"# {title}",
        "",
        f"> **{snapshot.item_count}** trending items from **{len(snapshot.sources_queried)}** sources",
        f"> Generated: {ts}",
        "",
    ]

    # ── Top items by source ──
    for source in SourceType:
        items = snapshot.by_source(source)
        if not items:
            continue

        emoji = SOURCE_EMOJI.get(source, "•")
        items_sorted = sorted(items, key=lambda x: x.score, reverse=True)

        lines.append(f"## {emoji} {source.value.upper()}")
        lines.append("")
        lines.append("| # | Title | Score | Details |")
        lines.append("|---|-------|-------|---------|")

        for i, item in enumerate(items_sorted[:top_n], 1):
            title_text = f"[{item.title}]({item.url})" if item.url else item.title
            score = item.score_display
            details = (item.description[:80] + "…") if len(item.description) > 80 else item.description
            details = details.replace("|", "/")
            lines.append(f"| {i} | {title_text} | ⭐{score} | {details} |")

        lines.append("")

    # ── Keywords ──
    if include_keywords:
        kw = snapshot.keywords(15)
        if kw:
            lines.append("## 🔑 Trending Keywords")
            lines.append("")
            keyword_strs = []
            for word, count in kw:
                if count >= 5:
                    badge = "🔥"
                elif count >= 3:
                    badge = "🟡"
                else:
                    badge = "⚪"
                keyword_strs.append(f"{badge} **{word}** ({count})")
            lines.append(" · ".join(keyword_strs))
            lines.append("")

    # ── Stats ──
    if include_stats:
        by_source = {}
        for item in snapshot.items:
            src = item.source.value
            by_source[src] = by_source.get(src, 0) + 1

        scores = [it.score for it in snapshot.items if it.score > 0]
        avg_score = sum(scores) / len(scores) if scores else 0

        lines.append("## 📊 Summary")
        lines.append("")
        lines.append(f"- **Total items:** {snapshot.item_count}")
        lines.append(f"- **Sources:** {', '.join(snapshot.sources_queried)}")
        lines.append(f"- **Average score:** {avg_score:.0f}")
        for src, count in sorted(by_source.items()):
            emoji = SOURCE_EMOJI.get(SourceType(src) if src != "producthunt" else SourceType.PRODUCTHUNT, "•")
            lines.append(f"- {emoji} {src}: {count} items")
        lines.append("")

    # ── Footer ──
    lines.append("---")
    lines.append(f"*Generated by [Trend Radar](https://github.com/Jane-o-O-o-O/trend-radar) — {ts}*")

    return "\n".join(lines)


def generate_digest_html(
    snapshot: TrendSnapshot,
    title: Optional[str] = None,
    top_n: int = 10,
) -> str:
    """Generate a beautiful standalone HTML digest report."""
    ts = snapshot.timestamp.strftime("%Y-%m-%d %H:%M UTC")
    title = title or f"Trend Radar Digest — {ts}"

    # Build source sections
    source_sections = []
    for source in SourceType:
        items = snapshot.by_source(source)
        if not items:
            continue

        emoji = SOURCE_EMOJI.get(source, "•")
        items_sorted = sorted(items, key=lambda x: x.score, reverse=True)

        rows = []
        for i, item in enumerate(items_sorted[:top_n], 1):
            title_html = f'<a href="{item.url}" style="color:#38bdf8;text-decoration:none">{item.title}</a>' if item.url else item.title
            desc = (item.description[:100] + "…") if len(item.description) > 100 else item.description
            rows.append(f"""
            <tr>
                <td style="padding:8px 12px;color:#64748b">{i}</td>
                <td style="padding:8px 12px">{title_html}</td>
                <td style="padding:8px 12px;text-align:right;font-weight:bold;color:#f59e0b">⭐{item.score_display}</td>
                <td style="padding:8px 12px;color:#94a3b8;font-size:0.9em">{desc}</td>
            </tr>""")

        source_sections.append(f"""
        <div style="margin-bottom:24px">
            <h2 style="color:#e2e8f0;font-size:1.2em;margin-bottom:12px">{emoji} {source.value.upper()}</h2>
            <table style="width:100%;border-collapse:collapse;background:#1e293b;border-radius:8px;overflow:hidden">
                <thead>
                    <tr style="background:#334155">
                        <th style="padding:10px 12px;text-align:left;color:#94a3b8;font-weight:600">#</th>
                        <th style="padding:10px 12px;text-align:left;color:#94a3b8;font-weight:600">Title</th>
                        <th style="padding:10px 12px;text-align:right;color:#94a3b8;font-weight:600">Score</th>
                        <th style="padding:10px 12px;text-align:left;color:#94a3b8;font-weight:600">Details</th>
                    </tr>
                </thead>
                <tbody>{"".join(rows)}</tbody>
            </table>
        </div>""")

    # Keywords
    kw = snapshot.keywords(15)
    kw_html = ""
    if kw:
        max_count = max(c for _, c in kw) if kw else 1
        kw_items = []
        for word, count in kw:
            pct = int(count / max_count * 100)
            color = "#ef4444" if count >= 5 else "#f59e0b" if count >= 3 else "#64748b"
            kw_items.append(f"""
            <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px">
                <span style="color:{color};font-weight:600;min-width:100px">{word}</span>
                <div style="flex:1;background:#1e293b;border-radius:4px;height:20px;overflow:hidden">
                    <div style="width:{pct}%;height:100%;background:linear-gradient(90deg,#06b6d4,#3b82f6);border-radius:4px"></div>
                </div>
                <span style="color:#94a3b8;font-size:0.85em">{count}</span>
            </div>""")
        kw_html = f"""
        <div style="margin-bottom:24px">
            <h2 style="color:#e2e8f0;font-size:1.2em;margin-bottom:12px">🔑 Trending Keywords</h2>
            {"".join(kw_items)}
        </div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif; background: #0f172a; color: #e2e8f0; padding: 24px; }}
        .container {{ max-width: 1000px; margin: 0 auto; }}
        h1 {{ font-size: 1.8em; margin-bottom: 8px; color: #38bdf8; }}
        .subtitle {{ color: #64748b; margin-bottom: 24px; font-size: 0.95em; }}
        a {{ color: #38bdf8; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📡 {title}</h1>
        <p class="subtitle">{snapshot.item_count} items from {len(snapshot.sources_queried)} sources · {ts}</p>
        {"".join(source_sections)}
        {kw_html}
        <hr style="border:none;border-top:1px solid #334155;margin:24px 0">
        <p style="color:#475569;font-size:0.85em;text-align:center">
            Generated by <a href="https://github.com/Jane-o-O-o-O/trend-radar">Trend Radar</a> · {ts}
        </p>
    </div>
</body>
</html>"""

# [2026-06-08] source aggregation
class SourceAggregationHandler:
    """Handler for source aggregation operations."""

    def __init__(self, config: dict = None):
        self._config = config or {}
        self._initialized = False
        self._cache = {}

    def initialize(self) -> bool:
        """Initialize the handler with current configuration."""
        if self._initialized:
            return True
        try:
            self._validate_config()
            self._initialized = True
            return True
        except Exception as e:
            logger.warning(f"Initialization failed: {e}")
            return False

    def _validate_config(self):
        """Validate configuration parameters."""
        required = self._required_keys()
        missing = [k for k in required if k not in self._config]
        if missing:
            raise ValueError(f"Missing config keys: {missing}")

    def _required_keys(self) -> list:
        return ["enabled"]

    def process(self, data: dict) -> dict:
        """Process data through the handler."""
        if not self._initialized:
            self.initialize()
        result = self._transform(data)
        self._cache[data.get("id", "default")] = result
        return result

    def _transform(self, data: dict) -> dict:
        """Apply transformation to input data."""
        return {"status": "processed", "data": data, "handler": self.__class__.__name__}

    def clear_cache(self):
        """Clear the internal cache."""
        self._cache.clear()
