"""Obsidian-compatible markdown export for Trend Radar.

Exports trends as Obsidian-friendly markdown files with YAML frontmatter,
wikilinks, tags, and daily note formatting.
"""

from datetime import datetime, timezone
from typing import Optional

from .models import IntelItem, SourceType, TrendSnapshot


SOURCE_EMOJI = {
    "github": "🐙",
    "hackernews": "🔶",
    "reddit": "🤖",
    "arxiv": "📄",
    "rss": "📡",
    "producthunt": "🚀",
}


def _format_score(score: int) -> str:
    if score >= 1000:
        return f"{score / 1000:.1f}k"
    return str(score)


def _source_tags(items: list[IntelItem]) -> list[str]:
    """Extract unique source names as tags."""
    return sorted({item.source.value for item in items})


def _keyword_tags(items: list[IntelItem]) -> list[str]:
    """Extract keyword tags from items."""
    from .models import STOP_WORDS
    import re

    word_freq: dict[str, int] = {}
    for item in items:
        words = re.findall(r"[a-z]{3,}", item.title.lower())
        for w in words:
            if w not in STOP_WORDS:
                word_freq[w] = word_freq.get(w, 0) + 1

    # Top keywords as tags
    sorted_words = sorted(word_freq.items(), key=lambda x: -x[1])
    return [w for w, c in sorted_words[:15] if c >= 2]


def export_obsidian_daily(
    snapshot: TrendSnapshot,
    title: Optional[str] = None,
) -> str:
    """Export a snapshot as an Obsidian daily note.

    Creates a markdown file with YAML frontmatter suitable for
    Obsidian's daily notes plugin and Dataview queries.
    """
    now = snapshot.timestamp or datetime.now(timezone.utc)
    date_str = now.strftime("%Y-%m-%d")
    title = title or f"Trend Radar — {date_str}"

    sources = _source_tags(snapshot.items)
    keywords = _keyword_tags(snapshot.items)

    # YAML frontmatter
    lines = [
        "---",
        f"title: \"{title}\"",
        f"date: {date_str}",
        f"created: {now.isoformat()}",
        "type: trend-radar",
        f"total_items: {len(snapshot.items)}",
        f"sources_queried: {snapshot.sources_queried}",
        "tags:",
        "  - trend-radar",
        "  - tech-trends",
    ]
    for kw in keywords:
        lines.append(f"  - {kw}")
    lines.append("---")
    lines.append("")

    # Header
    lines.append(f"# 📡 {title}")
    lines.append("")
    lines.append(f"> Generated by [[Trend Radar]] on {now.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"> Sources: {', '.join(sources)} · {len(snapshot.items)} items")
    lines.append("")

    # Group by source
    by_source: dict[str, list[IntelItem]] = {}
    for item in snapshot.items:
        by_source.setdefault(item.source.value, []).append(item)

    for source_name, items in sorted(by_source.items()):
        emoji = SOURCE_EMOJI.get(source_name, "📌")
        lines.append(f"## {emoji} {source_name.title()}")
        lines.append("")

        for i, item in enumerate(sorted(items, key=lambda x: -x.score)[:15], 1):
            score_str = _format_score(item.score)
            if item.url:
                lines.append(f"{i}. **[{item.title}]({item.url})** — {score_str}")
            else:
                lines.append(f"{i}. **{item.title}** — {score_str}")

            if item.description:
                desc = item.description[:200]
                lines.append(f"   > {desc}")

            if item.tags:
                tag_str = " ".join(f"#{t}" for t in item.tags[:5])
                lines.append(f"   {tag_str}")

            lines.append("")

    # Keywords section
    if keywords:
        lines.append("## 🔑 Trending Keywords")
        lines.append("")
        for kw in keywords:
            lines.append(f"- `#{kw}`")
        lines.append("")

    # Related notes section
    lines.append("## 🔗 Related")
    lines.append("")
    lines.append("- [[Trend Radar Setup]]")
    lines.append(f"- [[{date_str}]]")
    lines.append("")

    return "\n".join(lines)


def export_obsidian_vault(
    snapshot: TrendSnapshot,
    vault_dir: Optional[str] = None,
) -> dict[str, str]:
    """Export a snapshot as multiple Obsidian vault files.

    Returns a dict of {filename: content} for:
    - Daily note (main overview)
    - Per-source notes
    - MOC (Map of Content) note
    """
    now = snapshot.timestamp or datetime.now(timezone.utc)
    date_str = now.strftime("%Y-%m-%d")
    files: dict[str, str] = {}

    # Main daily note
    files[f"Daily Notes/{date_str}.md"] = export_obsidian_daily(snapshot)

    # Per-source notes
    by_source: dict[str, list[IntelItem]] = {}
    for item in snapshot.items:
        by_source.setdefault(item.source.value, []).append(item)

    for source_name, items in by_source.items():
        emoji = SOURCE_EMOJI.get(source_name, "📌")
        content = [
            "---",
            f"title: \"{source_name.title()} Trends — {date_str}\"",
            f"date: {date_str}",
            "type: trend-source",
            f"source: {source_name}",
            "tags:",
            "  - trend-radar",
            f"  - {source_name}",
            "---",
            "",
            f"# {emoji} {source_name.title()} Trends — {date_str}",
            "",
            f"> {len(items)} items from {source_name}",
            "",
        ]

        for i, item in enumerate(sorted(items, key=lambda x: -x.score), 1):
            score_str = _format_score(item.score)
            if item.url:
                content.append(f"{i}. **[{item.title}]({item.url})** — {score_str}")
            else:
                content.append(f"{i}. **{item.title}** — {score_str}")
            if item.author:
                content.append(f"   by {item.author}")
            content.append("")

        files[f"Trends/{source_name}/{date_str}.md"] = "\n".join(content)

    # MOC (Map of Content)
    moc = [
        "---",
        f"title: \"Trend Radar MOC — {date_str}\"",
        f"date: {date_str}",
        "type: trend-moc",
        "tags:",
        "  - trend-radar",
        "  - MOC",
        "---",
        "",
        f"# 📡 Trend Radar — {date_str}",
        "",
        f"**{len(snapshot.items)} items** from **{len(by_source)} sources**",
        "",
        "## Sources",
        "",
    ]
    for source_name in sorted(by_source.keys()):
        emoji = SOURCE_EMOJI.get(source_name, "📌")
        moc.append(f"- [[Trends/{source_name}/{date_str}|{emoji} {source_name.title()}]]")
    moc.extend(["", "## Daily Note", "", f"- [[Daily Notes/{date_str}]]", ""])

    files["Trend Radar MOC.md"] = "\n".join(moc)

    return files


def export_obsidian_item(item: IntelItem) -> str:
    """Export a single IntelItem as an Obsidian note with metadata."""
    now = item.fetched_at or datetime.now(timezone.utc)
    emoji = SOURCE_EMOJI.get(item.source.value, "📌")

    lines = [
        "---",
        f"title: \"{item.title}\"",
        f"source: {item.source.value}",
        f"url: \"{item.url}\"",
        f"score: {item.score}",
        f"author: \"{item.author}\"",
        f"fetched: {now.isoformat()}",
        "tags:",
        "  - trend-radar",
        f"  - {item.source.value}",
    ]
    for tag in item.tags[:10]:
        lines.append(f"  - {tag}")
    lines.extend([
        "---",
        "",
        f"# {emoji} {item.title}",
        "",
        f"- **Source:** {item.source.value}",
        f"- **Score:** {_format_score(item.score)}",
        f"- **URL:** [{item.url}]({item.url})",
    ])
    if item.author:
        lines.append(f"- **Author:** {item.author}")
    if item.description:
        lines.extend(["", "## Description", "", item.description])
    if item.tags:
        lines.extend(["", "## Tags", ""])
        for tag in item.tags:
            lines.append(f"#{tag}")
    lines.append("")

    return "\n".join(lines)
